/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tienda;

import Casillas.Personajes.*;
import Casillas.Personajes.Jugables;
import Listas.ListaException;
import com.mycompany.matanzamedieval.Componentes;
import com.mycompany.matanzamedieval.Menu;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author carlo
 */
public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    private Componentes componentes;
    private Menu menu;
    public Tienda(Componentes componentes, Menu menu) {
        this.componentes = componentes;
        this.menu = menu;
        initComponents();
        lblOro.setText(String.valueOf(componentes.getOro()));
        limpiarPantalla();
    }
    
    public Tienda(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOro = new javax.swing.JLabel();
        btnPersonajes = new javax.swing.JButton();
        btnObjetos = new javax.swing.JButton();
        btnMejoras = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        pnlInformacionObjeto = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblCantidadObjetos = new javax.swing.JLabel();
        lblObjeto = new javax.swing.JLabel();
        lblDescripcionObjeto = new javax.swing.JLabel();
        lblImagenObjeto = new javax.swing.JLabel();
        pnlObjetos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnSemilla = new javax.swing.JButton();
        btnElixir = new javax.swing.JButton();
        btnCapa = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblPrecioObjeto = new javax.swing.JLabel();
        btnComprarObjeto = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        pnlInformacionPersonaje = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblMovimiento = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        lblDaño = new javax.swing.JLabel();
        lblPersonaje = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        pnlPersonajes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCaballero = new javax.swing.JButton();
        btnArquero = new javax.swing.JButton();
        btnMago = new javax.swing.JButton();
        btnGigante = new javax.swing.JButton();
        btnDragon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        pnlMejoras = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPersonaje1 = new javax.swing.JLabel();
        jcbPersonajes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnMejorarVida = new javax.swing.JButton();
        btnMejorarDaño = new javax.swing.JButton();
        btnMejorarMovimiento = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOro.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        lblOro.setForeground(new java.awt.Color(255, 255, 255));
        lblOro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/oro.png"))); // NOI18N
        lblOro.setText("0");
        jPanel1.add(lblOro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        btnPersonajes.setBackground(new java.awt.Color(102, 0, 0));
        btnPersonajes.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnPersonajes.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonajes.setText("Personajes");
        btnPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonajesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPersonajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, -1));

        btnObjetos.setBackground(new java.awt.Color(102, 0, 0));
        btnObjetos.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnObjetos.setForeground(new java.awt.Color(255, 255, 255));
        btnObjetos.setText("Objetos");
        btnObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjetosActionPerformed(evt);
            }
        });
        jPanel1.add(btnObjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, -1));

        btnMejoras.setBackground(new java.awt.Color(102, 0, 0));
        btnMejoras.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnMejoras.setForeground(new java.awt.Color(255, 255, 255));
        btnMejoras.setText("Mejoras");
        btnMejoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMejorasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMejoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, -1));

        lblTitulo.setFont(new java.awt.Font("Dutch801 XBd BT", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setText("TIENDA");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel15.setText("Objeto");

        jLabel16.setText("Cantidad");

        jLabel19.setText("Descripcion");

        lblImagenObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/planicie.png"))); // NOI18N

        javax.swing.GroupLayout pnlInformacionObjetoLayout = new javax.swing.GroupLayout(pnlInformacionObjeto);
        pnlInformacionObjeto.setLayout(pnlInformacionObjetoLayout);
        pnlInformacionObjetoLayout.setHorizontalGroup(
            pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionObjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionObjetoLayout.createSequentialGroup()
                        .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(23, 23, 23)
                        .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidadObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblDescripcionObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblImagenObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlInformacionObjetoLayout.setVerticalGroup(
            pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionObjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionObjetoLayout.createSequentialGroup()
                        .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(lblObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(lblCantidadObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescripcionObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagenObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.add(pnlInformacionObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 440, 150));

        jLabel13.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 18)); // NOI18N
        jLabel13.setText("Objetos");

        btnSemilla.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnSemilla.setText("Semilla de la vida");
        btnSemilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemillaActionPerformed(evt);
            }
        });

        btnElixir.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnElixir.setText("Elixir verde");
        btnElixir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElixirActionPerformed(evt);
            }
        });

        btnCapa.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnCapa.setText("Capa de movilidad");
        btnCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapaActionPerformed(evt);
            }
        });

        jLabel14.setText("Precio");

        btnComprarObjeto.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnComprarObjeto.setText("Comprar");
        btnComprarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarObjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlObjetosLayout = new javax.swing.GroupLayout(pnlObjetos);
        pnlObjetos.setLayout(pnlObjetosLayout);
        pnlObjetosLayout.setHorizontalGroup(
            pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlObjetosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(46, 46, 46)
                .addComponent(lblPrecioObjeto)
                .addGap(121, 121, 121)
                .addComponent(btnComprarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(pnlObjetosLayout.createSequentialGroup()
                .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlObjetosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElixir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlObjetosLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel13)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlObjetosLayout.setVerticalGroup(
            pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSemilla)
                    .addComponent(btnElixir)
                    .addComponent(btnCapa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprarObjeto)
                    .addComponent(jLabel14)
                    .addComponent(lblPrecioObjeto))
                .addContainerGap())
        );

        jPanel1.add(pnlObjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 440, 370));

        btnRegresar.setBackground(new java.awt.Color(102, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 120, -1));

        jLabel2.setText("Personaje");

        jLabel4.setText("Vida");

        jLabel8.setText("Movimiento");

        jLabel7.setText("Daño");

        jLabel11.setText("Ataque");

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/planicie.png"))); // NOI18N

        javax.swing.GroupLayout pnlInformacionPersonajeLayout = new javax.swing.GroupLayout(pnlInformacionPersonaje);
        pnlInformacionPersonaje.setLayout(pnlInformacionPersonajeLayout);
        pnlInformacionPersonajeLayout.setHorizontalGroup(
            pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                        .addComponent(lblAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(23, 23, 23)
                                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDaño, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInformacionPersonajeLayout.setVerticalGroup(
            pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblVida, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblDaño, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(pnlInformacionPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 440, 150));

        jLabel1.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 18)); // NOI18N
        jLabel1.setText("Personajes");

        btnCaballero.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnCaballero.setText("Caballero");
        btnCaballero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaballeroActionPerformed(evt);
            }
        });

        btnArquero.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnArquero.setText("Arquero");
        btnArquero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArqueroActionPerformed(evt);
            }
        });

        btnMago.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnMago.setText("Mago");
        btnMago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMagoActionPerformed(evt);
            }
        });

        btnGigante.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnGigante.setText("Gigante");
        btnGigante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiganteActionPerformed(evt);
            }
        });

        btnDragon.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnDragon.setText("Dragon");
        btnDragon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDragonActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio");

        btnComprar.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPersonajesLayout = new javax.swing.GroupLayout(pnlPersonajes);
        pnlPersonajes.setLayout(pnlPersonajesLayout);
        pnlPersonajesLayout.setHorizontalGroup(
            pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPersonajesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addComponent(lblPrecio)
                .addGap(121, 121, 121)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(pnlPersonajesLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonajesLayout.createSequentialGroup()
                        .addComponent(btnCaballero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(pnlPersonajesLayout.createSequentialGroup()
                                .addComponent(btnArquero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlPersonajesLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnGigante, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDragon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlPersonajesLayout.setVerticalGroup(
            pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaballero)
                    .addComponent(btnArquero)
                    .addComponent(btnMago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGigante)
                    .addComponent(btnDragon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprar)
                    .addComponent(jLabel6)
                    .addComponent(lblPrecio))
                .addContainerGap())
        );

        jPanel1.add(pnlPersonajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 440, 370));

        jLabel3.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 18)); // NOI18N
        jLabel3.setText("Mejoras");

        jcbPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPersonajesActionPerformed(evt);
            }
        });

        jLabel5.setText("Personajes en Inventario");

        btnMejorarVida.setText("+50 VIda");
        btnMejorarVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMejorarVidaActionPerformed(evt);
            }
        });

        btnMejorarDaño.setText("+10 Daño");
        btnMejorarDaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMejorarDañoActionPerformed(evt);
            }
        });

        btnMejorarMovimiento.setText("+1 Movimiento");
        btnMejorarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMejorarMovimientoActionPerformed(evt);
            }
        });

        jLabel9.setText("Precio: 80");

        jLabel10.setText("Precio: 125");

        jLabel12.setText("Precio: 500");

        javax.swing.GroupLayout pnlMejorasLayout = new javax.swing.GroupLayout(pnlMejoras);
        pnlMejoras.setLayout(pnlMejorasLayout);
        pnlMejorasLayout.setHorizontalGroup(
            pnlMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMejorasLayout.createSequentialGroup()
                .addGroup(pnlMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMejorasLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblPersonaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMejorasLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel3))
                    .addGroup(pnlMejorasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbPersonajes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlMejorasLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(pnlMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMejorarVida, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMejorarDaño, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMejorarMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnlMejorasLayout.setVerticalGroup(
            pnlMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMejorasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblPersonaje1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(pnlMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMejorarVida)
                    .addComponent(btnMejorarDaño)
                    .addComponent(btnMejorarMovimiento))
                .addContainerGap())
        );

        jPanel1.add(pnlMejoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 440, 370));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpeg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonajesActionPerformed
        limpiarPantalla();
        pnlPersonajes.setVisible(true);
        
        btnComprar.setVisible(false);
    }//GEN-LAST:event_btnPersonajesActionPerformed

    private void btnCaballeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaballeroActionPerformed
        personajeComprar = new Caballero();
        pnlInformacionPersonaje.setVisible(true);
        setearLabelsPersonajes(personajeComprar);
        btnComprar.setVisible(true);
    }//GEN-LAST:event_btnCaballeroActionPerformed

    private void btnArqueroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArqueroActionPerformed
        personajeComprar = new Arquero();
        pnlInformacionPersonaje.setVisible(true);
        setearLabelsPersonajes(personajeComprar);
        btnComprar.setVisible(true);
    }//GEN-LAST:event_btnArqueroActionPerformed

    private void btnMagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMagoActionPerformed
        personajeComprar = new Mago();
        pnlInformacionPersonaje.setVisible(true);
        setearLabelsPersonajes(personajeComprar);
        btnComprar.setVisible(true);
    }//GEN-LAST:event_btnMagoActionPerformed

    private void btnGiganteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiganteActionPerformed
        personajeComprar = new Gigante();
        pnlInformacionPersonaje.setVisible(true);
        setearLabelsPersonajes(personajeComprar);
        btnComprar.setVisible(true);
    }//GEN-LAST:event_btnGiganteActionPerformed

    private void btnDragonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDragonActionPerformed
        personajeComprar = new Dragon();
        pnlInformacionPersonaje.setVisible(true);
        setearLabelsPersonajes(personajeComprar);
        btnComprar.setVisible(true);
    }//GEN-LAST:event_btnDragonActionPerformed

    private Jugables personajeComprar;
    
    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        personajeComprar.comprar(componentes);
        actualizarOro();
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnMejorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMejorasActionPerformed
        limpiarPantalla();
        pnlMejoras.setVisible(true);
        personajesEnInventario();
    }//GEN-LAST:event_btnMejorasActionPerformed

    private void jcbPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPersonajesActionPerformed
        //Se actualizan los datos en el panel de información
        pnlInformacionPersonaje.setVisible(true);
        try {
            setearLabelsPersonajes(componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()));
        } catch (ListaException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbPersonajesActionPerformed

    private void btnMejorarVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMejorarVidaActionPerformed
        try {
            componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()).mejorarVida(componentes);
            setearLabelsPersonajes(componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()));
            actualizarOro();
        } catch (ListaException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMejorarVidaActionPerformed

    private void btnMejorarDañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMejorarDañoActionPerformed
        try {
            componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()).mejorarDaño(componentes);
            setearLabelsPersonajes(componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()));
            actualizarOro();
        } catch (ListaException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMejorarDañoActionPerformed

    private void btnMejorarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMejorarMovimientoActionPerformed
        try {
            componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()).mejorarMovimiento(componentes);
            setearLabelsPersonajes(componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()));
            actualizarOro();
        } catch (ListaException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMejorarMovimientoActionPerformed

    //OBJETOS
    //0=Semilla de la vida 1=Elixir verde 2=Capa de movilidad
    private int objetoSeleccionado;
    
    private void btnSemillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemillaActionPerformed
        objetoSeleccionado = 0;
        pnlInformacionObjeto.setVisible(true);
        setearLabelsObjetos();
        btnComprarObjeto.setVisible(true);
    }//GEN-LAST:event_btnSemillaActionPerformed

    private void btnElixirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElixirActionPerformed
        objetoSeleccionado = 1;
        pnlInformacionObjeto.setVisible(true);
        setearLabelsObjetos();
        btnComprarObjeto.setVisible(true);
    }//GEN-LAST:event_btnElixirActionPerformed

    private void btnCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapaActionPerformed
        objetoSeleccionado = 2;
        pnlInformacionObjeto.setVisible(true);
        setearLabelsObjetos();
        btnComprarObjeto.setVisible(true);
    }//GEN-LAST:event_btnCapaActionPerformed

    private void btnComprarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarObjetoActionPerformed
        try {
            componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).comprar(componentes);
            setearLabelsObjetos();
        } catch (ListaException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
        actualizarOro();
    }//GEN-LAST:event_btnComprarObjetoActionPerformed

    private void btnObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjetosActionPerformed
        limpiarPantalla();
        pnlObjetos.setVisible(true);
        btnComprarObjeto.setVisible(false);
    }//GEN-LAST:event_btnObjetosActionPerformed

    private void setearLabelsObjetos() {
        try {
            lblObjeto.setText(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getNombreObjeto());
            lblCantidadObjetos.setText(String.valueOf(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getCantidadDisponible()));
            lblDescripcionObjeto.setText(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getDescripcion());
            lblPrecioObjeto.setText(String.valueOf(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getPrecio()));
            
            //ImageIcon imagenIcono = new ImageIcon("src\\main\\java\\imagenes\\" + jugable.getNombre().toLowerCase() + ".png");
            ImageIcon imagenIcono = new ImageIcon(getClass().getResource(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getRuta()));
            Image imagen = imagenIcono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon imagenFinal = new ImageIcon(imagen);
            lblImagenObjeto.setIcon(imagenFinal);
        } catch (ListaException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setearLabelsPersonajes(Jugables jugable) {
        lblPersonaje.setText(jugable.getNombre());
        lblVida.setText(String.valueOf(jugable.getVida()));
        lblMovimiento.setText(jugable.getMovimiento());
        lblDaño.setText(String.valueOf(jugable.getDaño()));
        lblAtaque.setText(jugable.getAtaque());
        lblPrecio.setText(String.valueOf(200));

        //ImageIcon imagenIcono = new ImageIcon("src\\main\\java\\imagenes\\" + jugable.getNombre().toLowerCase() + ".png");
        ImageIcon imagenIcono = new ImageIcon(getClass().getResource(jugable.getRuta()));
        Image imagen = imagenIcono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon imagenFinal = new ImageIcon(imagen);
        lblImagen.setIcon(imagenFinal);
    }
    
    //OTROS
    private void limpiarPantalla(){
        pnlPersonajes.setVisible(false);
        pnlMejoras.setVisible(false);
        pnlObjetos.setVisible(false);
        
        pnlInformacionPersonaje.setVisible(false);
        pnlInformacionObjeto.setVisible(false);
    }
    
    private void actualizarOro(){
        lblOro.setText(String.valueOf(componentes.getOro()));
    }
    
    //Método para obtener los personajes en inventario
    private void personajesEnInventario(){
        jcbPersonajes.removeAllItems();
        for (int i = 0; i < componentes.getPersonajesJugables().obtenerSize(); i++) {
            try {
                jcbPersonajes.addItem(componentes.getPersonajesJugables().obtenerValor(i).getNickName());
            } catch (ListaException ex) {
                Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArquero;
    private javax.swing.JButton btnCaballero;
    private javax.swing.JButton btnCapa;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnComprarObjeto;
    private javax.swing.JButton btnDragon;
    private javax.swing.JButton btnElixir;
    private javax.swing.JButton btnGigante;
    private javax.swing.JButton btnMago;
    private javax.swing.JButton btnMejorarDaño;
    private javax.swing.JButton btnMejorarMovimiento;
    private javax.swing.JButton btnMejorarVida;
    private javax.swing.JButton btnMejoras;
    private javax.swing.JButton btnObjetos;
    private javax.swing.JButton btnPersonajes;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSemilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbPersonajes;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblCantidadObjetos;
    private javax.swing.JLabel lblDaño;
    private javax.swing.JLabel lblDescripcionObjeto;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagenObjeto;
    private javax.swing.JLabel lblMovimiento;
    private javax.swing.JLabel lblObjeto;
    private javax.swing.JLabel lblOro;
    private javax.swing.JLabel lblPersonaje;
    private javax.swing.JLabel lblPersonaje1;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioObjeto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVida;
    private javax.swing.JPanel pnlInformacionObjeto;
    private javax.swing.JPanel pnlInformacionPersonaje;
    private javax.swing.JPanel pnlMejoras;
    private javax.swing.JPanel pnlObjetos;
    private javax.swing.JPanel pnlPersonajes;
    // End of variables declaration//GEN-END:variables
}
