/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inventario;

import Casillas.Personajes.Jugables;
import Listas.ListaException;
import Partida.Partida;
import Partida.SeleccionDificultad;
import Tienda.Tienda;
import com.mycompany.matanzamedieval.Componentes;
import com.mycompany.matanzamedieval.Menu;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    private Componentes componentes;
    private Menu menu;
    public Inventario(Componentes componentes, Menu menu) {
        initComponents();
        this.componentes = componentes;
        this.menu = menu;
        limpiarPantalla();
        actualizarOro();
    }
    
    private int opcionMapa;
    public Inventario(Componentes componentes, int opcionMapa, Menu menu) {
        initComponents();
        this.componentes = componentes;
        this.opcionMapa = opcionMapa;
        this.menu = menu;
        limpiarPantalla();
        //Ocultamos el botón objetos
        btnObjetos.setVisible(false);
        btnPersonajes.setVisible(false);
        pnlPersonajes.setVisible(true);
        personajesEnInventario();
        pnlCombatientesSeleccionar.setVisible(true);
        actualizarOro();
    }
    
    public Inventario(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnObjetos = new javax.swing.JButton();
        btnPersonajes = new javax.swing.JButton();
        pnlInformacionPersonaje = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblMovimiento = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        lblDaño = new javax.swing.JLabel();
        lblPersonaje = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        pnlPersonajes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPersonaje1 = new javax.swing.JLabel();
        jcbPersonajes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        pnlCombatientesSeleccionar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCombatiente1 = new javax.swing.JLabel();
        lblCombatiente2 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        pnlObjetos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnSemilla = new javax.swing.JButton();
        btnElixir = new javax.swing.JButton();
        btnCapa = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblPrecioObjeto = new javax.swing.JLabel();
        btnVenderObjeto = new javax.swing.JButton();
        pnlInformacionObjeto = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblCantidadObjetos = new javax.swing.JLabel();
        lblObjeto = new javax.swing.JLabel();
        lblDescripcionObjeto = new javax.swing.JLabel();
        lblImagenObjeto = new javax.swing.JLabel();
        lblOro = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Dutch801 XBd BT", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setText("INVENTARIO");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(102, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 120, -1));

        btnObjetos.setBackground(new java.awt.Color(102, 0, 0));
        btnObjetos.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnObjetos.setForeground(new java.awt.Color(255, 255, 255));
        btnObjetos.setText("Objetos");
        btnObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjetosActionPerformed(evt);
            }
        });
        jPanel1.add(btnObjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, -1));

        btnPersonajes.setBackground(new java.awt.Color(102, 0, 0));
        btnPersonajes.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnPersonajes.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonajes.setText("Personajes");
        btnPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonajesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPersonajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, -1));

        jLabel2.setText("Personaje");

        jLabel4.setText("Vida");

        jLabel8.setText("Movimiento");

        jLabel7.setText("Daño");

        jLabel11.setText("Ataque");

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/planicie.png"))); // NOI18N

        javax.swing.GroupLayout pnlInformacionPersonajeLayout = new javax.swing.GroupLayout(pnlInformacionPersonaje);
        pnlInformacionPersonaje.setLayout(pnlInformacionPersonajeLayout);
        pnlInformacionPersonajeLayout.setHorizontalGroup(
            pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                        .addComponent(lblAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(23, 23, 23)
                                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDaño, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInformacionPersonajeLayout.setVerticalGroup(
            pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionPersonajeLayout.createSequentialGroup()
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblVida, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInformacionPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblDaño, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(pnlInformacionPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 440, 150));

        jLabel3.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 18)); // NOI18N
        jLabel3.setText("Personajes");

        jcbPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPersonajesActionPerformed(evt);
            }
        });

        jLabel5.setText("Personajes en Inventario");

        jLabel1.setText("Combatiente 1:");

        jLabel6.setText("Combatiente 2:");

        lblCombatiente1.setText("Ninguno");

        lblCombatiente2.setText("Ninguno");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCombatientesSeleccionarLayout = new javax.swing.GroupLayout(pnlCombatientesSeleccionar);
        pnlCombatientesSeleccionar.setLayout(pnlCombatientesSeleccionarLayout);
        pnlCombatientesSeleccionarLayout.setHorizontalGroup(
            pnlCombatientesSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCombatientesSeleccionarLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCombatiente1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlCombatientesSeleccionarLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCombatiente2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCombatientesSeleccionarLayout.setVerticalGroup(
            pnlCombatientesSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCombatientesSeleccionarLayout.createSequentialGroup()
                .addGroup(pnlCombatientesSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCombatiente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCombatientesSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCombatiente2)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCombatientesSeleccionarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeleccionar))
        );

        javax.swing.GroupLayout pnlPersonajesLayout = new javax.swing.GroupLayout(pnlPersonajes);
        pnlPersonajes.setLayout(pnlPersonajesLayout);
        pnlPersonajesLayout.setHorizontalGroup(
            pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonajesLayout.createSequentialGroup()
                .addGroup(pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonajesLayout.createSequentialGroup()
                        .addGroup(pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPersonajesLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(lblPersonaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPersonajesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jcbPersonajes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlPersonajesLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel3)))
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addGroup(pnlPersonajesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCombatientesSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPersonajesLayout.setVerticalGroup(
            pnlPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPersonajesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblPersonaje1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(pnlCombatientesSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pnlPersonajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 440, 370));

        jLabel13.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 18)); // NOI18N
        jLabel13.setText("Objetos");

        btnSemilla.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnSemilla.setText("Semilla de la vida");
        btnSemilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemillaActionPerformed(evt);
            }
        });

        btnElixir.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnElixir.setText("Elixir verde");
        btnElixir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElixirActionPerformed(evt);
            }
        });

        btnCapa.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnCapa.setText("Capa de movilidad");
        btnCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapaActionPerformed(evt);
            }
        });

        jLabel14.setText("Precio");

        btnVenderObjeto.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 12)); // NOI18N
        btnVenderObjeto.setText("Vender");
        btnVenderObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderObjetoActionPerformed(evt);
            }
        });

        jLabel15.setText("Objeto");

        jLabel16.setText("Cantidad");

        jLabel19.setText("Descripcion");

        lblImagenObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/planicie.png"))); // NOI18N

        javax.swing.GroupLayout pnlInformacionObjetoLayout = new javax.swing.GroupLayout(pnlInformacionObjeto);
        pnlInformacionObjeto.setLayout(pnlInformacionObjetoLayout);
        pnlInformacionObjetoLayout.setHorizontalGroup(
            pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionObjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionObjetoLayout.createSequentialGroup()
                        .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(23, 23, 23)
                        .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidadObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblDescripcionObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblImagenObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlInformacionObjetoLayout.setVerticalGroup(
            pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionObjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionObjetoLayout.createSequentialGroup()
                        .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(lblObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInformacionObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(lblCantidadObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescripcionObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagenObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlObjetosLayout = new javax.swing.GroupLayout(pnlObjetos);
        pnlObjetos.setLayout(pnlObjetosLayout);
        pnlObjetosLayout.setHorizontalGroup(
            pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlObjetosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(46, 46, 46)
                .addComponent(lblPrecioObjeto)
                .addGap(121, 121, 121)
                .addComponent(btnVenderObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(pnlObjetosLayout.createSequentialGroup()
                .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlObjetosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElixir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlObjetosLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel13)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlObjetosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInformacionObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlObjetosLayout.setVerticalGroup(
            pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSemilla)
                    .addComponent(btnElixir)
                    .addComponent(btnCapa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVenderObjeto)
                    .addComponent(jLabel14)
                    .addComponent(lblPrecioObjeto))
                .addContainerGap())
            .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlObjetosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInformacionObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(pnlObjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 440, 370));

        lblOro.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        lblOro.setForeground(new java.awt.Color(255, 255, 255));
        lblOro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/oro.png"))); // NOI18N
        lblOro.setText("0");
        jPanel1.add(lblOro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpeg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPersonajesActionPerformed
        //Se actualizan los datos en el panel de información
        pnlInformacionPersonaje.setVisible(true);
        
        try {
            setearLabelsPersonajes(componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()));
        } catch (ListaException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbPersonajesActionPerformed

    private void setearLabelsPersonajes(Jugables jugable) {
        lblPersonaje.setText(jugable.getNombre());
        lblVida.setText(String.valueOf(jugable.getVida()));
        lblMovimiento.setText(jugable.getMovimiento());
        lblDaño.setText(String.valueOf(jugable.getDaño()));
        lblAtaque.setText(jugable.getAtaque());

        //ImageIcon imagenIcono = new ImageIcon("src\\main\\java\\imagenes\\" + jugable.getNombre().toLowerCase() + ".png");
        ImageIcon imagenIcono = new ImageIcon(getClass().getResource(jugable.getRuta()));
        Image imagen = imagenIcono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon imagenFinal = new ImageIcon(imagen);
        lblImagen.setIcon(imagenFinal);
    }
    
    private void limpiarPantalla(){
        pnlPersonajes.setVisible(false);
        pnlInformacionPersonaje.setVisible(false);
        pnlObjetos.setVisible(false);
        pnlInformacionObjeto.setVisible(false);
        
        pnlCombatientesSeleccionar.setVisible(false);
    }
    
    private void actualizarOro(){
        lblOro.setText(String.valueOf(componentes.getOro()));
    }
    
    //Método para obtener los personajes en inventario
    private void personajesEnInventario(){
        jcbPersonajes.removeAllItems();
        for (int i = 0; i < componentes.getPersonajesJugables().obtenerSize(); i++) {
            try {
                jcbPersonajes.addItem(componentes.getPersonajesJugables().obtenerValor(i).getNickName());
            } catch (ListaException ex) {
                Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonajesActionPerformed
        limpiarPantalla();
        pnlPersonajes.setVisible(true);
        personajesEnInventario();
    }//GEN-LAST:event_btnPersonajesActionPerformed

    
    private int objetoSeleccionado;
    private void btnSemillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemillaActionPerformed
        objetoSeleccionado = 0;
        pnlInformacionObjeto.setVisible(true);
        setearLabelsObjetos();
        btnVenderObjeto.setVisible(true);
    }//GEN-LAST:event_btnSemillaActionPerformed

    private void btnElixirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElixirActionPerformed
        objetoSeleccionado = 1;
        pnlInformacionObjeto.setVisible(true);
        setearLabelsObjetos();
        btnVenderObjeto.setVisible(true);
    }//GEN-LAST:event_btnElixirActionPerformed

    private void btnCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapaActionPerformed
        objetoSeleccionado = 2;
        pnlInformacionObjeto.setVisible(true);
        setearLabelsObjetos();
        btnVenderObjeto.setVisible(true);
    }//GEN-LAST:event_btnCapaActionPerformed

    private void btnVenderObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderObjetoActionPerformed
        try {
            componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).vender(componentes);
            setearLabelsObjetos();
        } catch (ListaException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
        actualizarOro();
    }//GEN-LAST:event_btnVenderObjetoActionPerformed

    private void btnObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjetosActionPerformed
        limpiarPantalla();
        pnlObjetos.setVisible(true);
        btnVenderObjeto.setVisible(false);
    }//GEN-LAST:event_btnObjetosActionPerformed

    //Arreglo para almacenar a los jugadores seleccionados
    private Jugables[] jugablesPartida = new Jugables[2];
    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        if (lblCombatiente1.getText().equals("Ninguno")) {
            try {
                jugablesPartida[0] = (Jugables) componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()).clone();
                jugablesPartida[0] = componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex());
                lblCombatiente1.setText(jugablesPartida[0].getNickName());
                
                
                // Seteamos el item seleccionado al primero, luego de eliminar el item seleccionado
                //jcbPersonajes.removeItemAt(jcbPersonajes.getSelectedIndex());
                //jcbPersonajes.setSelectedIndex(1);
                //jcbPersonajesActionPerformed(evt);
            } catch (ListaException ex) {
                Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                // Se verifica que no seleccione el mismo jugador dos veces
                jugablesPartida[1] = (Jugables) componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex()).clone();
                jugablesPartida[1] = componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex());
                if (jugablesPartida[0] == jugablesPartida[1]) {
                    //Advertencia
                    JOptionPane.showMessageDialog(this, "Asegurese de seleccionar combatientes diferentes", "Valor inválido", JOptionPane.INFORMATION_MESSAGE);
                    
                } else{
                    lblCombatiente2.setText(jugablesPartida[1].getNickName());
                    //jugablesPartida[1] = componentes.getPersonajesJugables().obtenerValor(jcbPersonajes.getSelectedIndex());
                    
                    //Se llama el formulario para la selección de dificultad
                    SeleccionDificultad seleccionDificultad = new SeleccionDificultad(componentes, jugablesPartida, opcionMapa, menu);
                    seleccionDificultad.setLocationRelativeTo(null);
                    seleccionDificultad.setVisible(true);
                    this.dispose();
                }
                
            } catch (ListaException ex) {
                Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void setearLabelsObjetos() {
        try {
            lblObjeto.setText(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getNombreObjeto());
            lblCantidadObjetos.setText(String.valueOf(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getCantidadDisponible()));
            lblDescripcionObjeto.setText(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getDescripcion());
            lblPrecioObjeto.setText(String.valueOf(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getPrecio()));
            
            //ImageIcon imagenIcono = new ImageIcon("src\\main\\java\\imagenes\\" + jugable.getNombre().toLowerCase() + ".png");
            ImageIcon imagenIcono = new ImageIcon(getClass().getResource(componentes.getObjetosInventario().obtenerValor(objetoSeleccionado).getRuta()));
            Image imagen = imagenIcono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon imagenFinal = new ImageIcon(imagen);
            lblImagenObjeto.setIcon(imagenFinal);
        } catch (ListaException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapa;
    private javax.swing.JButton btnElixir;
    private javax.swing.JButton btnObjetos;
    private javax.swing.JButton btnPersonajes;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnSemilla;
    private javax.swing.JButton btnVenderObjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbPersonajes;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblCantidadObjetos;
    private javax.swing.JLabel lblCombatiente1;
    private javax.swing.JLabel lblCombatiente2;
    private javax.swing.JLabel lblDaño;
    private javax.swing.JLabel lblDescripcionObjeto;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagenObjeto;
    private javax.swing.JLabel lblMovimiento;
    private javax.swing.JLabel lblObjeto;
    private javax.swing.JLabel lblOro;
    private javax.swing.JLabel lblPersonaje;
    private javax.swing.JLabel lblPersonaje1;
    private javax.swing.JLabel lblPrecioObjeto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVida;
    private javax.swing.JPanel pnlCombatientesSeleccionar;
    private javax.swing.JPanel pnlInformacionObjeto;
    private javax.swing.JPanel pnlInformacionPersonaje;
    private javax.swing.JPanel pnlObjetos;
    private javax.swing.JPanel pnlPersonajes;
    // End of variables declaration//GEN-END:variables
}
