/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Archivos;

import com.mycompany.matanzamedieval.Menu;

/**
 *
 * @author carlo
 */
public class Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */
    private static Menu menu;
    private Archivos archivo = new Archivos();
    private String[] puntajes;
    
    public Ranking(Menu menu) {
        initComponents();
        this.menu = menu;
        
        puntajes = archivo.leerPuntajes();
        mostrarPuntajes(puntajes);
    }
    
    public Ranking(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeneral = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        pnlOrdenamiento = new javax.swing.JPanel();
        btnMayMen = new javax.swing.JButton();
        btnMenMay = new javax.swing.JButton();
        pnlVistaPuntajes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPuntajes = new javax.swing.JTextArea();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlGeneral.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 120, -1));

        btnMayMen.setText("Mayor a menor");
        btnMayMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayMenActionPerformed(evt);
            }
        });

        btnMenMay.setText("Menor a mayor");
        btnMenMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenMayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOrdenamientoLayout = new javax.swing.GroupLayout(pnlOrdenamiento);
        pnlOrdenamiento.setLayout(pnlOrdenamientoLayout);
        pnlOrdenamientoLayout.setHorizontalGroup(
            pnlOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrdenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMenMay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMayMen, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOrdenamientoLayout.setVerticalGroup(
            pnlOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMayMen)
                .addGap(18, 18, 18)
                .addComponent(btnMenMay)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        pnlGeneral.add(pnlOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 330));

        txtAreaPuntajes.setColumns(20);
        txtAreaPuntajes.setRows(5);
        jScrollPane1.setViewportView(txtAreaPuntajes);

        javax.swing.GroupLayout pnlVistaPuntajesLayout = new javax.swing.GroupLayout(pnlVistaPuntajes);
        pnlVistaPuntajes.setLayout(pnlVistaPuntajesLayout);
        pnlVistaPuntajesLayout.setHorizontalGroup(
            pnlVistaPuntajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVistaPuntajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVistaPuntajesLayout.setVerticalGroup(
            pnlVistaPuntajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVistaPuntajesLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlGeneral.add(pnlVistaPuntajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 400));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpeg"))); // NOI18N
        pnlGeneral.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMayMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayMenActionPerformed
        puntajes = archivo.ordanamientoPuntajes(puntajes, 0);
        mostrarPuntajes(puntajes);
    }//GEN-LAST:event_btnMayMenActionPerformed

    private void btnMenMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenMayActionPerformed
        puntajes = archivo.ordanamientoPuntajes(puntajes, 1);
        mostrarPuntajes(puntajes);
    }//GEN-LAST:event_btnMenMayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }
    
    public void mostrarPuntajes(String[] puntajes){
        txtAreaPuntajes.setText("");
        for (int i = 0; i < puntajes.length; i++) {
            if (puntajes[0] == null) {
                //No hay puntajes
                txtAreaPuntajes.setText("No hay puntajes disponibles");
                break;
            } else{
                if (puntajes[i] != null) {
                    txtAreaPuntajes.setText(txtAreaPuntajes.getText()+"\n"+(i+1) +". "+ puntajes[i]);
                } else{
                    break;
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMayMen;
    private javax.swing.JButton btnMenMay;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JPanel pnlOrdenamiento;
    private javax.swing.JPanel pnlVistaPuntajes;
    private javax.swing.JTextArea txtAreaPuntajes;
    // End of variables declaration//GEN-END:variables
}
